INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (1, N'AF        ', N'AFGHANISTAN', N'Afghanistan', N'AFG', 4, 93)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (2, N'AL        ', N'ALBANIA', N'Albania', N'ALB', 8, 355)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (3, N'DZ        ', N'ALGERIA', N'Algeria', N'DZA', 12, 213)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (4, N'AS        ', N'AMERICAN SAMOA', N'American Samoa', N'ASM', 16, 1684)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (5, N'AD        ', N'ANDORRA', N'Andorra', N'AND', 20, 376)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (6, N'AO        ', N'ANGOLA', N'Angola', N'AGO', 24, 244)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (7, N'AI        ', N'ANGUILLA', N'Anguilla', N'AIA', 660, 1264)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (8, N'AQ        ', N'ANTARCTICA', N'Antarctica', NULL, NULL, 0)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (9, N'AG        ', N'ANTIGUA AND BARBUDA', N'Antigua and Barbuda', N'ATG', 28, 1268)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (10, N'AR        ', N'ARGENTINA', N'Argentina', N'ARG', 32, 54)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (11, N'AM        ', N'ARMENIA', N'Armenia', N'ARM', 51, 374)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (12, N'AW        ', N'ARUBA', N'Aruba', N'ABW', 533, 297)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (13, N'AU        ', N'AUSTRALIA', N'Australia', N'AUS', 36, 61)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (14, N'AT        ', N'AUSTRIA', N'Austria', N'AUT', 40, 43)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (15, N'AZ        ', N'AZERBAIJAN', N'Azerbaijan', N'AZE', 31, 994)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (16, N'BS        ', N'BAHAMAS', N'Bahamas', N'BHS', 44, 1242)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (17, N'BH        ', N'BAHRAIN', N'Bahrain', N'BHR', 48, 973)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (18, N'BD        ', N'BANGLADESH', N'Bangladesh', N'BGD', 50, 880)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (19, N'BB        ', N'BARBADOS', N'Barbados', N'BRB', 52, 1246)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (20, N'BY        ', N'BELARUS', N'Belarus', N'BLR', 112, 375)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (21, N'BE        ', N'BELGIUM', N'Belgium', N'BEL', 56, 32)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (22, N'BZ        ', N'BELIZE', N'Belize', N'BLZ', 84, 501)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (23, N'BJ        ', N'BENIN', N'Benin', N'BEN', 204, 229)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (24, N'BM        ', N'BERMUDA', N'Bermuda', N'BMU', 60, 1441)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (25, N'BT        ', N'BHUTAN', N'Bhutan', N'BTN', 64, 975)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (26, N'BO        ', N'BOLIVIA', N'Bolivia', N'BOL', 68, 591)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (27, N'BA        ', N'BOSNIA AND HERZEGOVINA', N'Bosnia and Herzegovina', N'BIH', 70, 387)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (28, N'BW        ', N'BOTSWANA', N'Botswana', N'BWA', 72, 267)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (29, N'BV        ', N'BOUVET ISLAND', N'Bouvet Island', NULL, NULL, 0)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (30, N'BR        ', N'BRAZIL', N'Brazil', N'BRA', 76, 55)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (31, N'IO        ', N'BRITISH INDIAN OCEAN TERRITORY', N'British Indian Ocean Territory', NULL, NULL, 246)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (32, N'BN        ', N'BRUNEI DARUSSALAM', N'Brunei Darussalam', N'BRN', 96, 673)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (33, N'BG        ', N'BULGARIA', N'Bulgaria', N'BGR', 100, 359)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (34, N'BF        ', N'BURKINA FASO', N'Burkina Faso', N'BFA', 854, 226)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (35, N'BI        ', N'BURUNDI', N'Burundi', N'BDI', 108, 257)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (36, N'KH        ', N'CAMBODIA', N'Cambodia', N'KHM', 116, 855)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (37, N'CM        ', N'CAMEROON', N'Cameroon', N'CMR', 120, 237)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (38, N'CA        ', N'CANADA', N'Canada', N'CAN', 124, 1)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (39, N'CV        ', N'CAPE VERDE', N'Cape Verde', N'CPV', 132, 238)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (40, N'KY        ', N'CAYMAN ISLANDS', N'Cayman Islands', N'CYM', 136, 1345)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (41, N'CF        ', N'CENTRAL AFRICAN REPUBLIC', N'Central African Republic', N'CAF', 140, 236)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (42, N'TD        ', N'CHAD', N'Chad', N'TCD', 148, 235)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (43, N'CL        ', N'CHILE', N'Chile', N'CHL', 152, 56)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (44, N'CN        ', N'CHINA', N'China', N'CHN', 156, 86)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (45, N'CX        ', N'CHRISTMAS ISLAND', N'Christmas Island', NULL, NULL, 61)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (46, N'CC        ', N'COCOS (KEELING) ISLANDS', N'Cocos (Keeling) Islands', NULL, NULL, 672)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (47, N'CO        ', N'COLOMBIA', N'Colombia', N'COL', 170, 57)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (48, N'KM        ', N'COMOROS', N'Comoros', N'COM', 174, 269)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (49, N'CG        ', N'CONGO', N'Congo', N'COG', 178, 242)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (50, N'CD        ', N'CONGO', N' THE DEMOCRATIC REPUBLIC OF THE CONGO', N'COD', 180, 242)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (51, N'CK        ', N'COOK ISLANDS', N'Cook Islands', N'COK', 184, 682)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (52, N'CR        ', N'COSTA RICA', N'Costa Rica', N'CRI', 188, 506)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (53, N'CI        ', N'COTE D''IVOIRE', N'Cote D''Ivoire', N'CIV', 384, 225)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (54, N'HR        ', N'CROATIA', N'Croatia', N'HRV', 191, 385)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (55, N'CU        ', N'CUBA', N'Cuba', N'CUB', 192, 53)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (56, N'CY        ', N'CYPRUS', N'Cyprus', N'CYP', 196, 357)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (57, N'CZ        ', N'CZECH REPUBLIC', N'Czech Republic', N'CZE', 203, 420)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (58, N'DK        ', N'DENMARK', N'Denmark', N'DNK', 208, 45)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (59, N'DJ        ', N'DJIBOUTI', N'Djibouti', N'DJI', 262, 253)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (60, N'DM        ', N'DOMINICA', N'Dominica', N'DMA', 212, 1767)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (61, N'DO        ', N'DOMINICAN REPUBLIC', N'Dominican Republic', N'DOM', 214, 1809)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (62, N'EC        ', N'ECUADOR', N'Ecuador', N'ECU', 218, 593)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (63, N'EG        ', N'EGYPT', N'Egypt', N'EGY', 818, 20)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (64, N'SV        ', N'EL SALVADOR', N'El Salvador', N'SLV', 222, 503)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (65, N'GQ        ', N'EQUATORIAL GUINEA', N'Equatorial Guinea', N'GNQ', 226, 240)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (66, N'ER        ', N'ERITREA', N'Eritrea', N'ERI', 232, 291)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (67, N'EE        ', N'ESTONIA', N'Estonia', N'EST', 233, 372)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (68, N'ET        ', N'ETHIOPIA', N'Ethiopia', N'ETH', 231, 251)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (69, N'FK        ', N'FALKLAND ISLANDS (MALVINAS)', N'Falkland Islands (Malvinas)', N'FLK', 238, 500)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (70, N'FO        ', N'FAROE ISLANDS', N'Faroe Islands', N'FRO', 234, 298)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (71, N'FJ        ', N'FIJI', N'Fiji', N'FJI', 242, 679)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (72, N'FI        ', N'FINLAND', N'Finland', N'FIN', 246, 358)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (73, N'FR        ', N'FRANCE', N'France', N'FRA', 250, 33)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (74, N'GF        ', N'FRENCH GUIANA', N'French Guiana', N'GUF', 254, 594)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (75, N'PF        ', N'FRENCH POLYNESIA', N'French Polynesia', N'PYF', 258, 689)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (76, N'TF        ', N'FRENCH SOUTHERN TERRITORIES', N'French Southern Territories', NULL, NULL, 0)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (77, N'GA        ', N'GABON', N'Gabon', N'GAB', 266, 241)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (78, N'GM        ', N'GAMBIA', N'Gambia', N'GMB', 270, 220)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (79, N'GE        ', N'GEORGIA', N'Georgia', N'GEO', 268, 995)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (80, N'DE        ', N'GERMANY', N'Germany', N'DEU', 276, 49)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (81, N'GH        ', N'GHANA', N'Ghana', N'GHA', 288, 233)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (82, N'GI        ', N'GIBRALTAR', N'Gibraltar', N'GIB', 292, 350)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (83, N'GR        ', N'GREECE', N'Greece', N'GRC', 300, 30)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (84, N'GL        ', N'GREENLAND', N'Greenland', N'GRL', 304, 299)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (85, N'GD        ', N'GRENADA', N'Grenada', N'GRD', 308, 1473)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (86, N'GP        ', N'GUADELOUPE', N'Guadeloupe', N'GLP', 312, 590)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (87, N'GU        ', N'GUAM', N'Guam', N'GUM', 316, 1671)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (88, N'GT        ', N'GUATEMALA', N'Guatemala', N'GTM', 320, 502)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (89, N'GN        ', N'GUINEA', N'Guinea', N'GIN', 324, 224)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (90, N'GW        ', N'GUINEA-BISSAU', N'Guinea-Bissau', N'GNB', 624, 245)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (91, N'GY        ', N'GUYANA', N'Guyana', N'GUY', 328, 592)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (92, N'HT        ', N'HAITI', N'Haiti', N'HTI', 332, 509)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (93, N'HM        ', N'HEARD ISLAND AND MCDONALD ISLANDS', N'Heard Island and Mcdonald Islands', NULL, NULL, 0)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (94, N'VA        ', N'HOLY SEE (VATICAN CITY STATE)', N'Holy See (Vatican City State)', N'VAT', 336, 39)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (95, N'HN        ', N'HONDURAS', N'Honduras', N'HND', 340, 504)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (96, N'HK        ', N'HONG KONG', N'Hong Kong', N'HKG', 344, 852)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (97, N'HU        ', N'HUNGARY', N'Hungary', N'HUN', 348, 36)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (98, N'IS        ', N'ICELAND', N'Iceland', N'ISL', 352, 354)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (99, N'IN        ', N'INDIA', N'India', N'IND', 356, 91)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (100, N'ID        ', N'INDONESIA', N'Indonesia', N'IDN', 360, 62)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (101, N'IR        ', N'IRAN', N' ISLAMIC REPUBLIC OF IRAN', NULL, 364, 98)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (102, N'IQ        ', N'IRAQ', N'Iraq', N'IRQ', 368, 964)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (103, N'IE        ', N'IRELAND', N'Ireland', N'IRL', 372, 353)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (104, N'IL        ', N'ISRAEL', N'Israel', N'ISR', 376, 972)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (105, N'IT        ', N'ITALY', N'Italy', N'ITA', 380, 39)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (106, N'JM        ', N'JAMAICA', N'Jamaica', N'JAM', 388, 1876)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (107, N'JP        ', N'JAPAN', N'Japan', N'JPN', 392, 81)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (108, N'JO        ', N'JORDAN', N'Jordan', N'JOR', 400, 962)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (109, N'KZ        ', N'KAZAKHSTAN', N'Kazakhstan', N'KAZ', 398, 7)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (110, N'KE        ', N'KENYA', N'Kenya', N'KEN', 404, 254)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (111, N'KI        ', N'KIRIBATI', N'Kiribati', N'KIR', 296, 686)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (112, N'KP        ', N'KOREA', N' DEMOCRATIC PEOPLE''S REPUBLIC OF Korea', N'PRK', 408, 850)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (113, N'KR        ', N'KOREA', N' REPUBLIC OF Korea', N'KOR', 410, 82)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (114, N'KW        ', N'KUWAIT', N'Kuwait', N'KWT', 414, 965)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (115, N'KG        ', N'KYRGYZSTAN', N'Kyrgyzstan', N'KGZ', 417, 996)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (116, N'LA        ', N'LAO PEOPLE''S DEMOCRATIC REPUBLIC', N'Lao People''s Democratic Republic', N'LAO', 418, 856)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (117, N'LV        ', N'LATVIA', N'Latvia', N'LVA', 428, 371)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (118, N'LB        ', N'LEBANON', N'Lebanon', N'LBN', 422, 961)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (119, N'LS        ', N'LESOTHO', N'Lesotho', N'LSO', 426, 266)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (120, N'LR        ', N'LIBERIA', N'Liberia', N'LBR', 430, 231)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (121, N'LY        ', N'LIBYAN ARAB JAMAHIRIYA', N'Libyan Arab Jamahiriya', N'LBY', 434, 218)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (122, N'LI        ', N'LIECHTENSTEIN', N'Liechtenstein', N'LIE', 438, 423)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (123, N'LT        ', N'LITHUANIA', N'Lithuania', N'LTU', 440, 370)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (124, N'LU        ', N'LUXEMBOURG', N'Luxembourg', N'LUX', 442, 352)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (125, N'MO        ', N'MACAO', N'Macao', N'MAC', 446, 853)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (126, N'MK        ', N'MACEDONIA', N' THE FORMER YUGOSLAV REPUBLIC OF Macedonia', N'MKD', 807, 389)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (127, N'MG        ', N'MADAGASCAR', N'Madagascar', N'MDG', 450, 261)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (128, N'MW        ', N'MALAWI', N'Malawi', N'MWI', 454, 265)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (129, N'MY        ', N'MALAYSIA', N'Malaysia', N'MYS', 458, 60)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (130, N'MV        ', N'MALDIVES', N'Maldives', N'MDV', 462, 960)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (131, N'ML        ', N'MALI', N'Mali', N'MLI', 466, 223)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (132, N'MT        ', N'MALTA', N'Malta', N'MLT', 470, 356)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (133, N'MH        ', N'MARSHALL ISLANDS', N'Marshall Islands', N'MHL', 584, 692)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (134, N'MQ        ', N'MARTINIQUE', N'Martinique', N'MTQ', 474, 596)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (135, N'MR        ', N'MAURITANIA', N'Mauritania', N'MRT', 478, 222)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (136, N'MU        ', N'MAURITIUS', N'Mauritius', N'MUS', 480, 230)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (137, N'YT        ', N'MAYOTTE', N'Mayotte', NULL, NULL, 269)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (138, N'MX        ', N'MEXICO', N'Mexico', N'MEX', 484, 52)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (139, N'FM        ', N'MICRONESIA', N' FEDERATED STATES OF Micronesia', N'FSM', 583, 691)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (140, N'MD        ', N'MOLDOVA', N' REPUBLIC OF Moldova', N'MDA', 498, 373)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (141, N'MC        ', N'MONACO', N'Monaco', N'MCO', 492, 377)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (142, N'MN        ', N'MONGOLIA', N'Mongolia', N'MNG', 496, 976)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (143, N'MS        ', N'MONTSERRAT', N'Montserrat', N'MSR', 500, 1664)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (144, N'MA        ', N'MOROCCO', N'Morocco', N'MAR', 504, 212)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (145, N'MZ        ', N'MOZAMBIQUE', N'Mozambique', N'MOZ', 508, 258)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (146, N'MM        ', N'MYANMAR', N'Myanmar', N'MMR', 104, 95)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (147, N'NA        ', N'NAMIBIA', N'Namibia', N'NAM', 516, 264)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (148, N'NR        ', N'NAURU', N'Nauru', N'NRU', 520, 674)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (149, N'NP        ', N'NEPAL', N'Nepal', N'NPL', 524, 977)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (150, N'NL        ', N'NETHERLANDS', N'Netherlands', N'NLD', 528, 31)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (151, N'AN        ', N'NETHERLANDS ANTILLES', N'Netherlands Antilles', N'ANT', 530, 599)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (152, N'NC        ', N'NEW CALEDONIA', N'New Caledonia', N'NCL', 540, 687)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (153, N'NZ        ', N'NEW ZEALAND', N'New Zealand', N'NZL', 554, 64)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (154, N'NI        ', N'NICARAGUA', N'Nicaragua', N'NIC', 558, 505)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (155, N'NE        ', N'NIGER', N'Niger', N'NER', 562, 227)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (156, N'NG        ', N'NIGERIA', N'Nigeria', N'NGA', 566, 234)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (157, N'NU        ', N'NIUE', N'Niue', N'NIU', 570, 683)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (158, N'NF        ', N'NORFOLK ISLAND', N'Norfolk Island', N'NFK', 574, 672)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (159, N'MP        ', N'NORTHERN MARIANA ISLANDS', N'Northern Mariana Islands', N'MNP', 580, 1670)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (160, N'NO        ', N'NORWAY', N'Norway', N'NOR', 578, 47)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (161, N'OM        ', N'OMAN', N'Oman', N'OMN', 512, 968)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (162, N'PK        ', N'PAKISTAN', N'Pakistan', N'PAK', 586, 92)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (163, N'PW        ', N'PALAU', N'Palau', N'PLW', 585, 680)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (164, N'PS        ', N'PALESTINIAN TERRITORY', N' OCCUPIED Palestinian Territory', NULL, NULL, 970)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (165, N'PA        ', N'PANAMA', N'Panama', N'PAN', 591, 507)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (166, N'PG        ', N'PAPUA NEW GUINEA', N'Papua New Guinea', N'PNG', 598, 675)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (167, N'PY        ', N'PARAGUAY', N'Paraguay', N'PRY', 600, 595)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (168, N'PE        ', N'PERU', N'Peru', N'PER', 604, 51)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (169, N'PH        ', N'PHILIPPINES', N'Philippines', N'PHL', 608, 63)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (170, N'PN        ', N'PITCAIRN', N'Pitcairn', N'PCN', 612, 0)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (171, N'PL        ', N'POLAND', N'Poland', N'POL', 616, 48)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (172, N'PT        ', N'PORTUGAL', N'Portugal', N'PRT', 620, 351)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (173, N'PR        ', N'PUERTO RICO', N'Puerto Rico', N'PRI', 630, 1787)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (174, N'QA        ', N'QATAR', N'Qatar', N'QAT', 634, 974)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (175, N'RE        ', N'REUNION', N'Reunion', N'REU', 638, 262)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (176, N'RO        ', N'ROMANIA', N'Romania', N'ROM', 642, 40)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (177, N'RU        ', N'RUSSIAN FEDERATION', N'Russian Federation', N'RUS', 643, 70)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (178, N'RW        ', N'RWANDA', N'Rwanda', N'RWA', 646, 250)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (179, N'SH        ', N'SAINT HELENA', N'Saint Helena', N'SHN', 654, 290)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (180, N'KN        ', N'SAINT KITTS AND NEVIS', N'Saint Kitts and Nevis', N'KNA', 659, 1869)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (181, N'LC        ', N'SAINT LUCIA', N'Saint Lucia', N'LCA', 662, 1758)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (182, N'PM        ', N'SAINT PIERRE AND MIQUELON', N'Saint Pierre and Miquelon', N'SPM', 666, 508)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (183, N'VC        ', N'SAINT VINCENT AND THE GRENADINES', N'Saint Vincent and the Grenadines', N'VCT', 670, 1784)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (184, N'WS        ', N'SAMOA', N'Samoa', N'WSM', 882, 684)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (185, N'SM        ', N'SAN MARINO', N'San Marino', N'SMR', 674, 378)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (186, N'ST        ', N'SAO TOME AND PRINCIPE', N'Sao Tome and Principe', N'STP', 678, 239)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (187, N'SA        ', N'SAUDI ARABIA', N'Saudi Arabia', N'SAU', 682, 966)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (188, N'SN        ', N'SENEGAL', N'Senegal', N'SEN', 686, 221)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (189, N'CS        ', N'SERBIA AND MONTENEGRO', N'Serbia and Montenegro', NULL, NULL, 381)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (190, N'SC        ', N'SEYCHELLES', N'Seychelles', N'SYC', 690, 248)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (191, N'SL        ', N'SIERRA LEONE', N'Sierra Leone', N'SLE', 694, 232)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (192, N'SG        ', N'SINGAPORE', N'Singapore', N'SGP', 702, 65)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (193, N'SK        ', N'SLOVAKIA', N'Slovakia', N'SVK', 703, 421)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (194, N'SI        ', N'SLOVENIA', N'Slovenia', N'SVN', 705, 386)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (195, N'SB        ', N'SOLOMON ISLANDS', N'Solomon Islands', N'SLB', 90, 677)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (196, N'SO        ', N'SOMALIA', N'Somalia', N'SOM', 706, 252)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (197, N'ZA        ', N'SOUTH AFRICA', N'South Africa', N'ZAF', 710, 27)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (198, N'GS        ', N'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', N'South Georgia and the South Sandwich Islands', NULL, NULL, 0)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (199, N'ES        ', N'SPAIN', N'Spain', N'ESP', 724, 34)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (200, N'LK        ', N'SRI LANKA', N'Sri Lanka', N'LKA', 144, 94)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (201, N'SD        ', N'SUDAN', N'Sudan', N'SDN', 736, 249)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (202, N'SR        ', N'SURINAME', N'Suriname', N'SUR', 740, 597)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (203, N'SJ        ', N'SVALBARD AND JAN MAYEN', N'Svalbard and Jan Mayen', N'SJM', 744, 47)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (204, N'SZ        ', N'SWAZILAND', N'Swaziland', N'SWZ', 748, 268)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (205, N'SE        ', N'SWEDEN', N'Sweden', N'SWE', 752, 46)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (206, N'CH        ', N'SWITZERLAND', N'Switzerland', N'CHE', 756, 41)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (207, N'SY        ', N'SYRIAN ARAB REPUBLIC', N'Syrian Arab Republic', N'SYR', 760, 963)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (208, N'TW        ', N'TAIWAN', N'Province of China', N'TWN', 158, 886)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (209, N'TJ        ', N'TAJIKISTAN', N'Tajikistan', N'TJK', 762, 992)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (210, N'TZ        ', N'TANZANIA', N' UNITED REPUBLIC OF Tanzania', N'TZA', 834, 255)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (211, N'TH        ', N'THAILAND', N'Thailand', N'THA', 764, 66)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (212, N'TL        ', N'TIMOR-LESTE', N'Timor-Leste', NULL, NULL, 670)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (213, N'TG        ', N'TOGO', N'Togo', N'TGO', 768, 228)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (214, N'TK        ', N'TOKELAU', N'Tokelau', N'TKL', 772, 690)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (215, N'TO        ', N'TONGA', N'Tonga', N'TON', 776, 676)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (216, N'TT        ', N'TRINIDAD AND TOBAGO', N'Trinidad and Tobago', N'TTO', 780, 1868)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (217, N'TN        ', N'TUNISIA', N'Tunisia', N'TUN', 788, 216)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (218, N'TR        ', N'TURKEY', N'Turkey', N'TUR', 792, 90)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (219, N'TM        ', N'TURKMENISTAN', N'Turkmenistan', N'TKM', 795, 7370)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (220, N'TC        ', N'TURKS AND CAICOS ISLANDS', N'Turks and Caicos Islands', N'TCA', 796, 1649)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (221, N'TV        ', N'TUVALU', N'Tuvalu', N'TUV', 798, 688)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (222, N'UG        ', N'UGANDA', N'Uganda', N'UGA', 800, 256)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (223, N'UA        ', N'UKRAINE', N'Ukraine', N'UKR', 804, 380)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (224, N'AE        ', N'UNITED ARAB EMIRATES', N'United Arab Emirates', N'ARE', 784, 971)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (225, N'GB        ', N'UNITED KINGDOM', N'United Kingdom', N'GBR', 826, 44)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (226, N'US        ', N'UNITED STATES', N'United States', N'USA', 840, 1)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (227, N'UM        ', N'UNITED STATES MINOR OUTLYING ISLANDS', N'United States Minor Outlying Islands', NULL, NULL, 1)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (228, N'UY        ', N'URUGUAY', N'Uruguay', N'URY', 858, 598)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (229, N'UZ        ', N'UZBEKISTAN', N'Uzbekistan', N'UZB', 860, 998)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (230, N'VU        ', N'VANUATU', N'Vanuatu', N'VUT', 548, 678)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (231, N'VE        ', N'VENEZUELA', N'Venezuela', N'VEN', 862, 58)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (232, N'VN        ', N'VIET NAM', N'Viet Nam', N'VNM', 704, 84)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (233, N'VG        ', N'VIRGIN ISLANDS', N' BRITISH Virgin Islands', N'VGB', 92, 1284)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (234, N'VI        ', N'VIRGIN ISLANDS', N' U.S. Virgin Islands', N'VIR', 850, 1340)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (235, N'WF        ', N'WALLIS AND FUTUNA', N'Wallis and Futuna', N'WLF', 876, 681)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (236, N'EH        ', N'WESTERN SAHARA', N'Western Sahara', N'ESH', 732, 212)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (237, N'YE        ', N'YEMEN', N'Yemen', N'YEM', 887, 967)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (238, N'ZM        ', N'ZAMBIA', N'Zambia', N'ZMB', 894, 260)
INSERT [dbo].[Country] ([Id], [Iso], [Name], [Nicename], [Iso3], [Numcode], [Phonecode]) VALUES (239, N'ZW        ', N'ZIMBABWE', N'Zimbabwe', N'ZWE', 716, 263)